/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package praktikummodul4;

import javax.swing.*;
import java.util.Random;
import java.util.ArrayList;
/**
 *
 * @author User
 */

public class TebakAngka extends javax.swing.JFrame {
    private int target;
    private int percobaan;
    private final int maxPercobaan = 10;
    private ArrayList<String> listSkor;

    /**
     * Creates new form TebakAngka
     */
    public TebakAngka() {
        initComponents();
        resetGame();
        listSkor = new ArrayList<>();
        System.out.println("target :" + target);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtTebakan = new javax.swing.JLabel();
        tftebakan = new javax.swing.JTextField();
        txtHint = new javax.swing.JLabel();
        tfscore = new javax.swing.JTextField();
        txtSkor = new javax.swing.JLabel();
        tfcek = new javax.swing.JTextField();
        btntebak = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        lbjudul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasilscore = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        resetscore = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTebakan.setBackground(new java.awt.Color(255, 255, 255));
        txtTebakan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTebakan.setForeground(new java.awt.Color(255, 255, 255));
        txtTebakan.setText("Tebakan:");
        jPanel1.add(txtTebakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        jPanel1.add(tftebakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 210, -1));

        txtHint.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtHint.setForeground(new java.awt.Color(255, 255, 255));
        txtHint.setText("Cek:");
        jPanel1.add(txtHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        jPanel1.add(tfscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, -1));

        txtSkor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSkor.setForeground(new java.awt.Color(255, 255, 255));
        txtSkor.setText("Score :");
        jPanel1.add(txtSkor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        tfcek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcekActionPerformed(evt);
            }
        });
        jPanel1.add(tfcek, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, -1));

        btntebak.setBackground(new java.awt.Color(204, 0, 204));
        btntebak.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btntebak.setForeground(new java.awt.Color(255, 255, 255));
        btntebak.setText("Tebak ()");
        btntebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntebakActionPerformed(evt);
            }
        });
        jPanel1.add(btntebak, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        btnreset.setBackground(new java.awt.Color(204, 0, 204));
        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        lbjudul.setBackground(new java.awt.Color(255, 255, 255));
        lbjudul.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lbjudul.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbjudul.setText("TEBAK ANGKA !!!");
        lbjudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 320, 40));

        jTabbedPane1.addTab("Game", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hasilscore.setBackground(new java.awt.Color(255, 102, 204));
        hasilscore.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(hasilscore);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 217));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SCORE!!!");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        resetscore.setBackground(new java.awt.Color(204, 0, 204));
        resetscore.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        resetscore.setForeground(new java.awt.Color(255, 255, 255));
        resetscore.setText("Reset");
        resetscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetscoreActionPerformed(evt);
            }
        });
        jPanel2.add(resetscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        keluar.setBackground(new java.awt.Color(204, 0, 204));
        keluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel2.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jTabbedPane1.addTab("Score", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        resetGame();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btntebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntebakActionPerformed
        // TODO add your handling code here:
        try {
            int tebakan = Integer.parseInt(tftebakan.getText().trim());
            if (tebakan < 1 || tebakan > 100) {
                JOptionPane.showMessageDialog(this, "Masukkan angka antara 1 dan 100!");
                return;
            }
            percobaan++;
            btntebak.setText("Sisa Percobaan: " + (maxPercobaan - percobaan));

            if (tebakan < target) {
                tfcek.setText("Angka terlalu kecil");
            } else if (tebakan > target) {
                tfcek.setText("Angka terlalu besar");
            } else {
                JOptionPane.showMessageDialog(this, "Anda Berhasil!");

                tfcek.setText("Aku Adalah Angka " + target);
                String nama = JOptionPane.showInputDialog(this, "Masukkan Nama Anda:");
                if (nama != null && !nama.trim().isEmpty()) {
                    int skor = (maxPercobaan - percobaan + 1) * 10;
                    listSkor.add(nama + " - Score: " + skor); 
                    updateDaftarSkor();
                }
                resetGame();
                return;
            }

            tfscore.setText(String.valueOf((maxPercobaan - percobaan) * 10));

            if (percobaan >= maxPercobaan) {
                JOptionPane.showMessageDialog(this, "Anda Gagal! Targetnya adalah: " + target);
                resetGame();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
        }
    }//GEN-LAST:event_btntebakActionPerformed

    private void tfcekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcekActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void resetscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetscoreActionPerformed
        // TODO add your handling code here:
        hasilscore.setListData(new String[0]);
    }//GEN-LAST:event_resetscoreActionPerformed
        private void resetGame(){
        target = new Random().nextInt(100) + 1;
        percobaan = 0;
        tfcek.setText("");
        tftebakan.setText("");
        tfscore.setText(String.valueOf(maxPercobaan * 10)); 
        tftebakan.setEnabled(true);
        btntebak.setText("Tebak: 10");
    }
    
    private void updateDaftarSkor() {
        hasilscore.setListData(listSkor.toArray(new String[0]));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntebak;
    private javax.swing.JList<String> hasilscore;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel lbjudul;
    private javax.swing.JButton resetscore;
    private javax.swing.JTextField tfcek;
    private javax.swing.JTextField tfscore;
    private javax.swing.JTextField tftebakan;
    private javax.swing.JLabel txtHint;
    private javax.swing.JLabel txtSkor;
    private javax.swing.JLabel txtTebakan;
    // End of variables declaration//GEN-END:variables

 
}
